name: Irene Y. Zhang
url: irenezhang.net
title: Irene Zhang
description: I am a researcher at Microsoft Research
    
exclude: [bibble, README.md, Makefile, job-search]

plugins:
   - jekyll-scholar
   
scholar:
   source: publications
   bibliography: pubs.bib
   bibliography_template: bibtemplate
   style: citesty
   locale: en
   replace_strings: true
   join_strings: true
  
# Permalinks
# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
front_page_news: 5