name: Irene Y. Zhang
url: irenezhang.net
title: Irene Zhang
description: I am a researcher at Microsoft Research
    
exclude: [README.md, Makefile, archive, _drafts, cv]

plugins:
   - jekyll-scholar

scholar:
   source: 
   bibliography: pubs.bib
   bibliography_template: bibtemplate
   style: citesty
   locale: en
   replace_strings: true
   join_strings: true
  
# Permalinks
# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
front_page_news: 5

base_url: ""

main_toc:
  - title: About
    url: ""
  - title: Research
    url: "research/"
  - title: Publications
    url: "publications/"
  - title: Students
    url: "students/"
  - title: Service
    url: "service/"
  - title: Blog
    url: "blog/"

