name: Irene Y. Zhang
url: 0.0.0.0:4000
exclude: [bibble, README.md, Makefile, job-search]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Number of news stories on the front page.
front_page_news: 3

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Service
      link: /service.html
    - title: Blog
      link: /news.html
    - title: Code
      link: /code.html
 #   - title: CV
 #     link: /cv/cv.pdf
